(delete 'width initial-frame-alist)
(delete 'height initial-frame-alist)
(delete 'top initial-frame-alist)
(delete 'left initial-frame-alist)
(setq initial-frame-alist (append (list
'(width . 156)
'(height . 55)
'(top . 119)
'(left . 139))
initial-frame-alist))
